# Modern Seasons
The Premier League seasons from the most recent, 2024-2025, back to 2017-2018, have a more rich format than 1992-1993 through 2016-2017. Presumably, this is due to the inclusion of the Opta-supplied expected goals and expected assists data.

In any case, the parsing of the HTML will have to be in (at least) two separate branches because of this.

In [1]:
from pathlib import Path

import pandas as pd
import polars as pl

In [ ]:
for f in sorted(
    p
    for p in Path("data/premier-league").glob("*.html")
    if p.is_file() and p.stat().st_size > 0
):
    try:
        df = pd.read_html(
            f,
            flavor="lxml",
            dtype_backend="pyarrow",
            encoding="utf-8",
        )[0]
    except:
        n_cols = None
    else:
        n_cols = df.shape[1]
    finally:
        print(f"{f.name}: {n_cols}")
else:
    del df

In [3]:
THIRTY_SEVEN_COLUMN_INDEX: tuple[tuple[str, str], ...] = (
    ("Demographics", "Rk"),
    ("Demographics", "Player"),
    ("Demographics", "Nation"),
    ("Demographics", "Pos"),
    ("Demographics", "Squad"),
    ("Demographics", "Age"),
    ("Demographics", "Born"),
    ("Playing Time", "MP"),
    ("Playing Time", "Starts"),
    ("Playing Time", "Min"),
    ("Playing Time", "90s"),
    ("Performance", "Gls"),
    ("Performance", "Ast"),
    ("Performance", "G+A"),
    ("Performance", "G-PK"),
    ("Performance", "PK"),
    ("Performance", "PKatt"),
    ("Performance", "CrdY"),
    ("Performance", "CrdR"),
    ("Expected", "xG"),
    ("Expected", "npxG"),
    ("Expected", "xAG"),
    ("Expected", "npxG+xAG"),
    ("Progression", "PrgC"),
    ("Progression", "PrgP"),
    ("Progression", "PrgR"),
    ("Per 90 Minutes", "Gls"),
    ("Per 90 Minutes", "Ast"),
    ("Per 90 Minutes", "G+A"),
    ("Per 90 Minutes", "G-PK"),
    ("Per 90 Minutes", "G+A-PK"),
    ("Per 90 Minutes", "xG"),
    ("Per 90 Minutes", "xAG"),
    ("Per 90 Minutes", "xG+xAG"),
    ("Per 90 Minutes", "npxG"),
    ("Per 90 Minutes", "npxG+xAG"),
    ("Matches", "hyperlink"),
)

TWENTY_FIVE_COLUMN_INDEX: tuple[tuple[str, str], ...] = (
    ("Demographics", "Rk"),
    ("Demographics", "Player"),
    ("Demographics", "Nation"),
    ("Demographics", "Pos"),
    ("Demographics", "Squad"),
    ("Demographics", "Age"),
    ("Demographics", "Born"),
    ("Playing Time", "MP"),
    ("Playing Time", "Starts"),
    ("Playing Time", "Min"),
    ("Playing Time", "90s"),
    ("Performance", "Gls"),
    ("Performance", "Ast"),
    ("Performance", "G+A"),
    ("Performance", "G-PK"),
    ("Performance", "PK"),
    ("Performance", "PKatt"),
    ("Performance", "CrdY"),
    ("Performance", "CrdR"),
    ("Per 90 Minutes", "Gls"),
    ("Per 90 Minutes", "Ast"),
    ("Per 90 Minutes", "G+A"),
    ("Per 90 Minutes", "G-PK"),
    ("Per 90 Minutes", "G+A-PK"),
    ("Matches", "hyperlink"),
)

CHAMPIONS = {
    "2024-2025": "Liverpool",
    "2023-2024": "Manchester City",
    "2022-2023": "Manchester City",
    "2021-2022": "Manchester City",
    "2020-2021": "Manchester City",
    "2019-2020": "Liverpool",
    "2018-2019": "Manchester City",
    "2017-2018": "Manchester City",
    "2016-2017": "Chelsea",
    "2015-2016": "Leicester City",
    "2014-2015": "Chelsea",
    "2013-2014": "Manchester City",
    "2012-2013": "Manchester Utd",
    "2011-2012": "Manchester City",
    "2010-2011": "Manchester Utd",
    "2009-2010": "Chelsea",
    "2008-2009": "Manchester Utd",
    "2007-2008": "Manchester Utd",
    "2006-2007": "Manchester Utd",
    "2005-2006": "Chelsea",
    "2004-2005": "Chelsea",
    "2003-2004": "Arsenal",
    "2002-2003": "Manchester Utd",
    "2001-2002": "Arsenal",
    "2000-2001": "Manchester Utd",
    "1999-2000": "Manchester Utd",
    "1998-1999": "Manchester Utd",
    "1997-1998": "Arsenal",
    "1996-1997": "Manchester Utd",
    "1995-1996": "Manchester Utd",
    "1994-1995": "Blackburn",
    "1993-1994": "Manchester Utd",
    "1992-1993": "Manchester Utd",
}

In [4]:
full_df = pd.read_html(
    Path("data/premier-league/fbref_2024-2025.html"),
    flavor="lxml",
    dtype_backend="pyarrow",
    encoding="utf-8",
)[0]

full_df.columns = THIRTY_SEVEN_COLUMN_INDEX
full_df.head()

  Demographics                                                            \
            Rk             Player   Nation    Pos        Squad Age  Born
0            1         Max Aarons  eng ENG     DF  Bournemouth  24  2000
1            2  Joshua Acheampong  eng ENG     DF      Chelsea  18  2006
2            3        Tyler Adams   us USA     MF  Bournemouth  25  1999
3            4   Tosin Adarabioyo  eng ENG     DF      Chelsea  26  1997
4            5      Simon Adingra   ci CIV  FW,MF     Brighton  22  2002

  Playing Time               ... Per 90 Minutes                           \
            MP Starts   Min  ...            Ast   G+A  G-PK G+A-PK    xG
0            3      1    86  ...            0.0   0.0   0.0    0.0   0.0
1            4      2   170  ...            0.0   0.0   0.0    0.0  0.12
2           28     21  1965  ...           0.14  0.14   0.0   0.14  0.07
3           22     15  1409  ...           0.06  0.13  0.06   0.13  0.06
4           29     12  1097  ...           0.16  0.33  0.16   0.33   0.2

                                Matches
    xAG xG+xAG  npxG npxG+xAG hyperlink
0   0.0    0.0   0.0      0.0   Matches
1   0.0   0.12  0.12     0.12   Matches
2  0.05   0.12  0.07     0.12   Matches
3  0.01   0.07  0.06     0.07   Matches
4   0.2    0.4   0.2      0.4   Matches

[5 rows x 37 columns]

In [5]:
small_df = pd.read_html(
    Path("data/premier-league/fbref_2015-2016.html"),
    flavor="lxml",
    dtype_backend="pyarrow",
    encoding="utf-8",
)[0]

small_df.columns = TWENTY_FIVE_COLUMN_INDEX
small_df.head()

  Demographics                                                             \
            Rk               Player   Nation Pos          Squad Age  Born
0            1  Patrick van Aanholt   nl NED  DF     Sunderland  24  1990
1            2       Rolando Aarons  eng ENG  MF  Newcastle Utd  19  1995
2            3           Almen Abdi   ch SUI  MF        Watford  28  1986
3            4        Tammy Abraham  eng ENG  FW        Chelsea  17  1997
4            5         Charlie Adam  sct SCO  MF     Stoke City  29  1985

  Playing Time               ... Performance                 Per 90 Minutes  \
            MP Starts   Min  ...          PK PKatt CrdY CrdR            Gls
0           33     33  2970  ...           0     0    2    0           0.12
1           10      3   381  ...           0     0    1    0           0.24
2           32     25  1974  ...           0     0    4    0           0.09
3            2      0    55  ...           0     0    0    0           0.00
4           22     12  1044  ...           0     0    6    1           0.09

                             Matches
    Ast   G+A  G-PK G+A-PK hyperlink
0  0.09  0.21  0.12   0.21   Matches
1  0.24  0.47  0.24   0.47   Matches
2  0.00  0.09  0.09   0.09   Matches
3  0.00  0.00  0.00   0.00   Matches
4  0.09  0.17  0.09   0.17   Matches

[5 rows x 25 columns]

In [6]:
small_df.columns

MultiIndex([(  'Demographics',        'Rk'),
            (  'Demographics',    'Player'),
            (  'Demographics',    'Nation'),
            (  'Demographics',       'Pos'),
            (  'Demographics',     'Squad'),
            (  'Demographics',       'Age'),
            (  'Demographics',      'Born'),
            (  'Playing Time',        'MP'),
            (  'Playing Time',    'Starts'),
            (  'Playing Time',       'Min'),
            (  'Playing Time',       '90s'),
            (   'Performance',       'Gls'),
            (   'Performance',       'Ast'),
            (   'Performance',       'G+A'),
            (   'Performance',      'G-PK'),
            (   'Performance',        'PK'),
            (   'Performance',     'PKatt'),
            (   'Performance',      'CrdY'),
            (   'Performance',      'CrdR'),
            ('Per 90 Minutes',       'Gls'),
            ('Per 90 Minutes',       'Ast'),
            ('Per 90 Minutes',       'G+A'),
            ('Per 90 Minutes',      'G-PK'),
            ('Per 90 Minutes',    'G+A-PK'),
            (       'Matches', 'hyperlink')],
           )

The `Rk` (rank) column is not helpful here, as it is just the default range index + 1, so we drop it. Also the -1th column is a Web hyperlink artifact and is useless. Without the rest of the birth date, the `Born` column doesn't seem to help anything because `Age` is included. All of the `Per 90 Minutes` columns can go, because they should be able to be re-calculated.

Desired Columns:
  - `Player`
  - `Squad`
  - `Age`
  - `Min` (minutes played)
  - `Gls` (goals)
  - `Ast` (assists)

In [7]:
small_df.loc[
    :, pd.IndexSlice[:, ["Squad", "Player", "Age", "Min", "Gls", "Ast"]]
][("Performance", "Gls")].value_counts(dropna=False)

(Performance, Gls)
0      295
1       89
2       55
3       28
5       23
Gls     22
4       21
6       11
8        7
11       6
7        6
9        5
10       3
24       2
12       2
13       2
15       2
16       1
25       1
18       1
17       1
Name: count, dtype: int64[pyarrow]

What is going on in the `Gls` column? It has 22 rows with value `"Gls"`, not a number?

In [8]:
valid = small_df.loc[
    (small_df.loc[:, ("Demographics", "Age")].str.isnumeric())
    & (small_df[("Performance", "Gls")].str.isnumeric())
    & (small_df[("Performance", "Ast")].str.isnumeric()),
    :
]
valid.loc[:, ("Performance", "Gls")] = valid.loc[:, ("Performance", "Gls")].astype("int16[pyarrow]")
valid.loc[:, ("Performance", "Ast")] = valid.loc[:, ("Performance", "Ast")].astype("int16[pyarrow]")

valid.loc[:, ("Performance", "Gls")].value_counts(dropna=False)

(Performance, Gls)
0     295
1      89
2      55
3      28
5      23
4      21
6      11
8       7
11      6
7       6
9       5
10      3
24      2
12      2
13      2
15      2
16      1
25      1
18      1
17      1
Name: count, dtype: int64[pyarrow]

In [9]:
valid.loc[
    :,
    pd.IndexSlice[
        ("Demographics", "Playing Time", "Performance"), ["Age", "Min", "Gls", "Ast"]
    ],
].astype("int16[pyarrow]")

    Demographics Playing Time Performance
             Age          Min         Gls Ast
0             24         2970           4   3
1             19          381           1   1
2             28         1974           2   0
3             17           55           0   0
4             29         1044           1   1
..           ...          ...         ...  ..
578           30         1065           1   2
579           30         1062           0   1
580           22         2488           2   1
581           28          788           3   0
582           20         1918           1   1

[561 rows x 4 columns]

In [10]:
desired = small_df.loc[
    :,
    pd.IndexSlice[
        ("Demographics", "Playing Time", "Performance"),
        ["Squad", "Player", "Age", "Min", "Gls", "Ast"],
    ],
]
desired

        Demographics                          Playing Time Performance
               Squad               Player Age          Min         Gls Ast
0         Sunderland  Patrick van Aanholt  24         2970           4   3
1      Newcastle Utd       Rolando Aarons  19          381           1   1
2            Watford           Almen Abdi  28         1974           2   0
3            Chelsea        Tammy Abraham  17           55           0   0
4         Stoke City         Charlie Adam  29         1044           1   1
..               ...                  ...  ..          ...         ...  ..
578   Manchester Utd         Ashley Young  30         1065           1   2
579  Manchester City       Pablo Zabaleta  30         1062           0   1
580   Crystal Palace        Wilfried Zaha  22         2488           2   1
581         West Ham         Mauro Zárate  28          788           3   0
582          Chelsea           Kurt Zouma  20         1918           1   1

[583 rows x 6 columns]

In [69]:
print(desired.columns.droplevel(0))
desired.columns = desired.columns.droplevel(0)
desired.head()

Index(['Squad', 'Player', 'Age', 'Min', 'Gls', 'Ast'], dtype='object')

           Squad               Player Age   Min Gls Ast
0     Sunderland  Patrick van Aanholt  24  2970   4   3
1  Newcastle Utd       Rolando Aarons  19   381   1   1
2        Watford           Almen Abdi  28  1974   2   0
3        Chelsea        Tammy Abraham  17    55   0   0
4     Stoke City         Charlie Adam  29  1044   1   1

In [11]:
def html_to_flat_dataframe(path_to_html: Path) -> pd.DataFrame:
    """The HTML will bring in a MultiIndex column; single-level index is desired."""
    html_read = pd.read_html(
        path_to_html, flavor="lxml", dtype_backend="pyarrow", encoding="utf-8"
    )
    df: pd.DataFrame = html_read[0]
    if df.shape[1] == 37:
        df.columns = THIRTY_SEVEN_COLUMN_INDEX
    elif df.shape[1] == 25:
        df.columns = TWENTY_FIVE_COLUMN_INDEX
    else:
        _msg: str = (
            f"Unexpected number of columns, {len(df)}, "
            f"from file '{path_to_html.resolve()}'."
        )
        raise RuntimeError(_msg)

    desired_columns: list[str, str, str, str, str, str] = [
        "Squad",
        "Player",
        "Age",
        "Min",
        "Gls",
        "Ast",
    ]
    # If Age, Gls, or Ast value is a non-number string,
    # it's an HTML parsing artifact and is to be dropped
    if df.shape[1] == 25:
        subset: pd.DataFrame = df.loc[
            (df.loc[:, ("Demographics", "Age")].str.isnumeric())
            & (df[("Performance", "Gls")].str.isnumeric())
            & (df[("Performance", "Ast")].str.isnumeric()),
            pd.IndexSlice[
                ("Demographics", "Playing Time", "Performance"),
                desired_columns,
            ],
        ].copy()
    else:
        subset: pd.DataFrame = df.loc[
            :,
            pd.IndexSlice[
                ("Demographics", "Playing Time", "Performance"),
                desired_columns,
            ],
        ].copy()
    subset.columns = subset.columns.droplevel(0)
    subset["Age"] = subset["Age"].astype("int16[pyarrow]")
    subset["Min"] = subset["Min"].astype("int16[pyarrow]")
    subset["Gls"] = subset["Gls"].astype("int16[pyarrow]")
    subset["Ast"] = subset["Ast"].astype("int16[pyarrow]")

    return subset

In [11]:
df16 = html_to_flat_dataframe(Path("data/premier-league/fbref_2015-2016.html"))

In [12]:
df16.dtypes

Squad     string[pyarrow]
Player    string[pyarrow]
Age        int16[pyarrow]
Min        int16[pyarrow]
Gls        int16[pyarrow]
Ast        int16[pyarrow]
dtype: object

## Season 2024-2025
Champions Liverpool

In [17]:
df25 = html_to_flat_dataframe(
    Path("data/premier-league/fbref_2024-2025.html")
).sort_values(by="Gls", ascending=False)

In [18]:
# pl.from_pandas(df25).sort(pl.col("Gls"), descending=True)
subset25 = pl.from_pandas(df25).filter(pl.col("Squad") == CHAMPIONS["2024-2025"])
subset25.with_columns(
    pl.col("Gls").truediv(pl.col("Gls").sum()).alias("prop_total_goals")
)

shape: (24, 7)
┌───────────┬────────────────────┬─────┬──────┬─────┬─────┬──────────────────┐
│ Squad     ┆ Player             ┆ Age ┆ Min  ┆ Gls ┆ Ast ┆ prop_total_goals │
│ ---       ┆ ---                ┆ --- ┆ ---  ┆ --- ┆ --- ┆ ---              │
│ str       ┆ str                ┆ i16 ┆ i16  ┆ i16 ┆ i16 ┆ f64              │
╞═══════════╪════════════════════╪═════╪══════╪═════╪═════╪══════════════════╡
│ Liverpool ┆ Mohamed Salah      ┆ 32  ┆ 3371 ┆ 29  ┆ 18  ┆ 0.341176         │
│ Liverpool ┆ Luis Díaz          ┆ 27  ┆ 2399 ┆ 13  ┆ 5   ┆ 0.152941         │
│ Liverpool ┆ Cody Gakpo         ┆ 25  ┆ 1935 ┆ 10  ┆ 4   ┆ 0.117647         │
│ Liverpool ┆ Diogo Jota         ┆ 27  ┆ 1196 ┆ 6   ┆ 3   ┆ 0.070588         │
│ Liverpool ┆ Dominik Szoboszlai ┆ 23  ┆ 2491 ┆ 6   ┆ 6   ┆ 0.070588         │
│ …         ┆ …                  ┆ …   ┆ …    ┆ …   ┆ …   ┆ …                │
│ Liverpool ┆ Vitezslav Jaros    ┆ 23  ┆ 12   ┆ 0   ┆ 0   ┆ 0.0              │
│ Liverpool ┆ Caoimhín Kelleher  ┆ 25  ┆ 900  ┆ 0   ┆ 0   ┆ 0.0              │
│ Liverpool ┆ Jarell Quansah     ┆ 21  ┆ 495  ┆ 0   ┆ 0   ┆ 0.0              │
│ Liverpool ┆ Andrew Robertson   ┆ 30  ┆ 2482 ┆ 0   ┆ 1   ┆ 0.0              │
│ Liverpool ┆ Kostas Tsimikas    ┆ 28  ┆ 837  ┆ 0   ┆ 1   ┆ 0.0              │
└───────────┴────────────────────┴─────┴──────┴─────┴─────┴──────────────────┘

## Season 2023-2024

In [15]:
df24 = pl.from_pandas(
    html_to_flat_dataframe(Path("data/premier-league/fbref_2023-2024.html"))
)
df24.filter(
    pl.col("Squad").eq(CHAMPIONS["2023-2024"])
).with_columns(
    pl.col("Gls").truediv(pl.col("Gls").sum()).alias("prop_total_goals").cast(pl.Float32)
).sort(by="Gls", descending=True)

shape: (25, 7)
┌─────────────────┬─────────────────┬─────┬──────┬─────┬─────┬──────────────────┐
│ Squad           ┆ Player          ┆ Age ┆ Min  ┆ Gls ┆ Ast ┆ prop_total_goals │
│ ---             ┆ ---             ┆ --- ┆ ---  ┆ --- ┆ --- ┆ ---              │
│ str             ┆ str             ┆ i16 ┆ i16  ┆ i16 ┆ i16 ┆ f32              │
╞═════════════════╪═════════════════╪═════╪══════╪═════╪═════╪══════════════════╡
│ Manchester City ┆ Erling Haaland  ┆ 23  ┆ 2552 ┆ 27  ┆ 5   ┆ 0.287234         │
│ Manchester City ┆ Phil Foden      ┆ 23  ┆ 2857 ┆ 19  ┆ 8   ┆ 0.202128         │
│ Manchester City ┆ Julián Álvarez  ┆ 23  ┆ 2647 ┆ 11  ┆ 8   ┆ 0.117021         │
│ Manchester City ┆ Rodri           ┆ 27  ┆ 2931 ┆ 8   ┆ 9   ┆ 0.085106         │
│ Manchester City ┆ Bernardo Silva  ┆ 28  ┆ 2578 ┆ 6   ┆ 9   ┆ 0.06383          │
│ …               ┆ …               ┆ …   ┆ …    ┆ …   ┆ …   ┆ …                │
│ Manchester City ┆ Matheus Nunes   ┆ 24  ┆ 661  ┆ 0   ┆ 2   ┆ 0.0              │
│ Manchester City ┆ Stefan Ortega   ┆ 30  ┆ 635  ┆ 0   ┆ 0   ┆ 0.0              │
│ Manchester City ┆ Cole Palmer     ┆ 21  ┆ 11   ┆ 0   ┆ 0   ┆ 0.0              │
│ Manchester City ┆ Kalvin Phillips ┆ 27  ┆ 93   ┆ 0   ┆ 0   ┆ 0.0              │
│ Manchester City ┆ Kyle Walker     ┆ 33  ┆ 2767 ┆ 0   ┆ 4   ┆ 0.0              │
└─────────────────┴─────────────────┴─────┴──────┴─────┴─────┴──────────────────┘

# Season 2022-2023

In [163]:
df23 = pl.from_pandas(
    html_to_flat_dataframe(Path("data/premier-league/fbref_2022-2023.html"))
)
df23.filter(
    pl.col("Squad").eq(CHAMPIONS["2022-2023"])
).with_columns(
    pl.col("Gls").truediv(pl.col("Gls").sum()).alias("prop_total_goals").cast(pl.Float32)
).sort(by="Gls", descending=True).slice(0, 1)

shape: (1, 7)
┌─────────────────┬────────────────┬─────┬──────┬─────┬─────┬──────────────────┐
│ Squad           ┆ Player         ┆ Age ┆ Min  ┆ Gls ┆ Ast ┆ prop_total_goals │
│ ---             ┆ ---            ┆ --- ┆ ---  ┆ --- ┆ --- ┆ ---              │
│ str             ┆ str            ┆ i16 ┆ i16  ┆ i16 ┆ i16 ┆ f32              │
╞═════════════════╪════════════════╪═════╪══════╪═════╪═════╪══════════════════╡
│ Manchester City ┆ Erling Haaland ┆ 22  ┆ 2769 ┆ 36  ┆ 8   ┆ 0.391304         │
└─────────────────┴────────────────┴─────┴──────┴─────┴─────┴──────────────────┘

# All Seasons, Iteratively
Let's do a `for` loop, but then make it prettier at some point

In [12]:
all_seasons: list[pl.DataFrame, ...] = [None] * len(CHAMPIONS)
for i, (season, champ) in enumerate(CHAMPIONS.items()):
    pldf = pl.from_pandas(
        html_to_flat_dataframe(Path(f"data/premier-league/fbref_{season}.html")),
    )
    max_prop_goals_for_champ: pl.DataFrame = (
        pldf.filter(pl.col("Squad").eq(champ))
        .with_columns(
            pl.lit(season).alias("Season"),
            pl.lit(champ).alias("Champion"),
            pl.col("Gls").sum().alias("total_goals").cast(pl.Int16),
            pl.col("Gls")
            .truediv(pl.col("Gls").sum())
            .alias("prop_total_goals")
            .cast(pl.Float32),
        )
        .sort(by="prop_total_goals", descending=True)
        .slice(0, 1)
    )
    all_seasons[i] = max_prop_goals_for_champ
    # print(f"SEASON {season}:\n\t{max_prop_goals_for_champ}")

In [13]:
print(
    pl.concat(all_seasons)
    .select(
        "Season",
        "Champion",
        "Player",
        "Gls",
        "total_goals",
        "prop_total_goals",
    )
    .sort(by="prop_total_goals", descending=True)
)

shape: (33, 6)
┌───────────┬─────────────────┬───────────────────┬─────┬─────────────┬──────────────────┐
│ Season    ┆ Champion        ┆ Player            ┆ Gls ┆ total_goals ┆ prop_total_goals │
│ ---       ┆ ---             ┆ ---               ┆ --- ┆ ---         ┆ ---              │
│ str       ┆ str             ┆ str               ┆ i16 ┆ i16         ┆ f32              │
╞═══════════╪═════════════════╪═══════════════════╪═════╪═════════════╪══════════════════╡
│ 1994-1995 ┆ Blackburn       ┆ Alan Shearer      ┆ 34  ┆ 78          ┆ 0.435897         │
│ 2003-2004 ┆ Arsenal         ┆ Thierry Henry     ┆ 30  ┆ 69          ┆ 0.434783         │
│ 2007-2008 ┆ Manchester Utd  ┆ Cristiano Ronaldo ┆ 31  ┆ 78          ┆ 0.397436         │
│ 2022-2023 ┆ Manchester City ┆ Erling Haaland    ┆ 36  ┆ 92          ┆ 0.391304         │
│ 2015-2016 ┆ Leicester City  ┆ Jamie Vardy       ┆ 24  ┆ 68          ┆ 0.352941         │
│ …         ┆ …               ┆ …                 ┆ …   ┆ …           ┆ …                │
│ 2000-2001 ┆ Manchester Utd  ┆ Teddy Sheringham  ┆ 15  ┆ 76          ┆ 0.197368         │
│ 1995-1996 ┆ Manchester Utd  ┆ Eric Cantona      ┆ 14  ┆ 72          ┆ 0.194444         │
│ 2004-2005 ┆ Chelsea         ┆ Frank Lampard     ┆ 13  ┆ 71          ┆ 0.183099         │
│ 2020-2021 ┆ Manchester City ┆ İlkay Gündoğan    ┆ 13  ┆ 82          ┆ 0.158537         │
│ 2021-2022 ┆ Manchester City ┆ Kevin De Bruyne   ┆ 15  ┆ 96          ┆ 0.15625          │
└───────────┴─────────────────┴───────────────────┴─────┴─────────────┴──────────────────┘

# Entire Scorer Distribution
First, need to get a data structure of `season: champion's goal distribution` which will be probably a `dict[str: array]`.

There certainly won't be the same amount of goal scorers per season, so there are three "standardization" approaches that come to mind:
  1. If there's always been a 25-man roster, then get the 25 names and there will just be a lot of mass on 0
  
   - Moreover, this is unreasonable because goalkeepers _almost never score_

  2. Very similar to (1) above: get the number of players who made an appearance and use _that_ as the support of the goals scored dist'n

   - Same problem with the goalkeepers never scoring, "artifically" inflating the support

  3. Subset the champions' squads to _just_ those who scored 1 goal: the support of the dist'n will be that number of players

   - This _feels_ more like the basis of a comparison-to-uniform; i.e., for those who pitched in: how far is the actual dist'n from an "egalitarian" goal spread?

Then, if it looks wonky for some reason, could do a further analysis that limits to _just_ the players that scored more than once (this would necessitate subtracting from the total goals) because those could be flukes, and see what the dist'n for those $P$ players is.

In [ ]:
# Start with Liverpool 2024-2025

In [19]:
goals25 = subset25.with_columns(
    prop_total_goals=pl.col("Gls").truediv(pl.col("Gls").sum())
)
goals25

shape: (24, 7)
┌───────────┬────────────────────┬─────┬──────┬─────┬─────┬──────────────────┐
│ Squad     ┆ Player             ┆ Age ┆ Min  ┆ Gls ┆ Ast ┆ prop_total_goals │
│ ---       ┆ ---                ┆ --- ┆ ---  ┆ --- ┆ --- ┆ ---              │
│ str       ┆ str                ┆ i16 ┆ i16  ┆ i16 ┆ i16 ┆ f64              │
╞═══════════╪════════════════════╪═════╪══════╪═════╪═════╪══════════════════╡
│ Liverpool ┆ Mohamed Salah      ┆ 32  ┆ 3371 ┆ 29  ┆ 18  ┆ 0.341176         │
│ Liverpool ┆ Luis Díaz          ┆ 27  ┆ 2399 ┆ 13  ┆ 5   ┆ 0.152941         │
│ Liverpool ┆ Cody Gakpo         ┆ 25  ┆ 1935 ┆ 10  ┆ 4   ┆ 0.117647         │
│ Liverpool ┆ Diogo Jota         ┆ 27  ┆ 1196 ┆ 6   ┆ 3   ┆ 0.070588         │
│ Liverpool ┆ Dominik Szoboszlai ┆ 23  ┆ 2491 ┆ 6   ┆ 6   ┆ 0.070588         │
│ …         ┆ …                  ┆ …   ┆ …    ┆ …   ┆ …   ┆ …                │
│ Liverpool ┆ Vitezslav Jaros    ┆ 23  ┆ 12   ┆ 0   ┆ 0   ┆ 0.0              │
│ Liverpool ┆ Caoimhín Kelleher  ┆ 25  ┆ 900  ┆ 0   ┆ 0   ┆ 0.0              │
│ Liverpool ┆ Jarell Quansah     ┆ 21  ┆ 495  ┆ 0   ┆ 0   ┆ 0.0              │
│ Liverpool ┆ Andrew Robertson   ┆ 30  ┆ 2482 ┆ 0   ┆ 1   ┆ 0.0              │
│ Liverpool ┆ Kostas Tsimikas    ┆ 28  ┆ 837  ┆ 0   ┆ 1   ┆ 0.0              │
└───────────┴────────────────────┴─────┴──────┴─────┴─────┴──────────────────┘

In [19]:
len(goals25)

24

In [15]:
from scipy.stats import energy_distance, wasserstein_distance

In [20]:
wasserstein_distance(
    [1 / goals25.shape[0]] * goals25.shape[0],
    goals25.select("prop_total_goals").to_series(),
)

np.float64(0.04824346405228758)

In [22]:
s = goals25.select("prop_total_goals").to_series()
s.filter(s > 0)

shape: (12,)
Series: 'prop_total_goals' [f64]
[
	0.341176
	0.152941
	0.117647
	0.070588
	0.070588
	…
	0.035294
	0.035294
	0.035294
	0.011765
	0.011765
]

In [23]:
wasserstein_distance(
    pl.Series((1/len(s.filter(s > 0)) for x in s.filter(s > 0))),
    s.filter(s > 0)
)

np.float64(0.06029411764705883)

In [24]:
wasserstein_distance(
    pl.Series([1.0] + [0.0]*(len(s.filter(s>0)) - 1)),
    s.filter(s > 0)
)

np.float64(0.10980392156862746)

In [25]:
pl.Series([1.0] + [0.0]*(len(s.filter(s>0)) - 1))

shape: (12,)
Series: '' [f64]
[
	1.0
	0.0
	0.0
	0.0
	0.0
	…
	0.0
	0.0
	0.0
	0.0
	0.0
]

In [21]:
def uniform_n(s: pl.Series) -> pl.Series:
    """Return a ``pl.Series`` populated by the scalar ``1 / len(s)``."""
    # a.k.a. flat Dirichlet distribution
    # https://en.wikipedia.org/wiki/Dirichlet_distribution#Special_cases
    return pl.Series(1/len(s) for _ in s)

In [27]:
energy_distance(
    [1 / len(goals25)] * len(goals25),
    goals25.select("prop_total_goals").to_series(),
)

np.float64(0.1866675420147543)

In [22]:
all_squads: list[pl.DataFrame, ...] = [None] * len(CHAMPIONS)

In [28]:
pldf = pl.from_pandas(html_to_flat_dataframe(Path(f"data/premier-league/fbref_{season}.html")))
pldf

shape: (562, 6)
┌─────────────────┬──────────────┬─────┬──────┬─────┬─────┐
│ Squad           ┆ Player       ┆ Age ┆ Min  ┆ Gls ┆ Ast │
│ ---             ┆ ---          ┆ --- ┆ ---  ┆ --- ┆ --- │
│ str             ┆ str          ┆ i16 ┆ i16  ┆ i16 ┆ i16 │
╞═════════════════╪══════════════╪═════╪══════╪═════╪═════╡
│ Everton         ┆ Gary Ablett  ┆ 26  ┆ 3600 ┆ 0   ┆ 2   │
│ Southampton     ┆ Micky Adams  ┆ 30  ┆ 3245 ┆ 4   ┆ 3   │
│ Oldham Athletic ┆ Neil Adams   ┆ 26  ┆ 2454 ┆ 8   ┆ 2   │
│ Arsenal         ┆ Tony Adams   ┆ 25  ┆ 3005 ┆ 0   ┆ 0   │
│ Southampton     ┆ Derek Allan  ┆ 17  ┆ 11   ┆ 0   ┆ 0   │
│ …               ┆ …            ┆ …   ┆ …    ┆ …   ┆ …   │
│ Middlesbrough   ┆ Tommy Wright ┆ 26  ┆ 3044 ┆ 5   ┆ 8   │
│ Ipswich Town    ┆ Frank Yallop ┆ 28  ┆ 452  ┆ 2   ┆ 0   │
│ Aston Villa     ┆ Dwight Yorke ┆ 20  ┆ 1918 ┆ 6   ┆ 3   │
│ Ipswich Town    ┆ Eddie Youds  ┆ 22  ┆ 1012 ┆ 0   ┆ 0   │
│ Crystal Palace  ┆ Eric Young   ┆ 32  ┆ 3085 ┆ 6   ┆ 0   │
└─────────────────┴──────────────┴─────┴──────┴─────┴─────┘

# All Seasons, Yo

In [66]:
l = [None] * len(CHAMPIONS)

for i, (season, champ) in enumerate(CHAMPIONS.items()):
    pdf = html_to_flat_dataframe(Path(f"data/premier-league/fbref_{season}.html"))
    pldf = pl.from_pandas(pdf)

    l[i] = pldf.with_columns(
        pl.col("Gls").sum().over(pl.col("Squad")).alias("total_goals").cast(pl.Int16),
        pl.col("Gls")
        .truediv(pl.col("Gls").sum().over(pl.col("Squad")))
        .alias("prop_total_goals")
        .cast(pl.Float32),
        season=pl.lit(season),
    )

    # l[i] = pldf.group_by("Squad").agg(
    #     pl.col("Gls").truediv(pl.col("Gls").sum()).max().alias("max_prop_goals"),
    # ).with_columns(season=pl.lit(season))

foo = pl.concat(l)


# with_columns(
#     pl.col("Gls").truediv(pl.col("Gls").sum()).alias("prop_total_goals").cast(pl.Float32),
# ).sort(by="Gls", descending=True).slice(0, 1)

In [71]:
with pl.Config(tbl_rows=-1, tbl_cols=-1):
    print(foo.sort(by="prop_total_goals", descending=True).select("season", "Squad", "Player", "Gls", "total_goals", "prop_total_goals").head(n=50))

shape: (50, 6)
┌───────────┬─────────────────┬───────────────────────────┬─────┬─────────────┬──────────────────┐
│ season    ┆ Squad           ┆ Player                    ┆ Gls ┆ total_goals ┆ prop_total_goals │
│ ---       ┆ ---             ┆ ---                       ┆ --- ┆ ---         ┆ ---              │
│ str       ┆ str             ┆ str                       ┆ i16 ┆ i16         ┆ f32              │
╞═══════════╪═════════════════╪═══════════════════════════╪═════╪═════════════╪══════════════════╡
│ 2002-2003 ┆ Southampton     ┆ James Beattie             ┆ 23  ┆ 42          ┆ 0.547619         │
│ 2016-2017 ┆ Sunderland      ┆ Jermain Defoe             ┆ 15  ┆ 28          ┆ 0.535714         │
│ 2009-2010 ┆ Sunderland      ┆ Darren Bent               ┆ 24  ┆ 45          ┆ 0.533333         │
│ 1999-2000 ┆ Sunderland      ┆ Kevin Phillips            ┆ 30  ┆ 57          ┆ 0.526316         │
│ 2021-2022 ┆ Norwich City    ┆ Teemu Pukki               ┆ 11  ┆ 21          ┆ 0.52381          │
│ 1995-1996 ┆ Blackburn       ┆ Alan Shearer              ┆ 31  ┆ 60          ┆ 0.516667         │
│ 2004-2005 ┆ Crystal Palace  ┆ Andrew Johnson            ┆ 21  ┆ 42          ┆ 0.5              │
│ 1993-1994 ┆ Southampton     ┆ Matt Le Tissier           ┆ 25  ┆ 50          ┆ 0.5              │
│ 1993-1994 ┆ Blackburn       ┆ Alan Shearer              ┆ 31  ┆ 63          ┆ 0.492063         │
│ 2014-2015 ┆ QPR             ┆ Charlie Austin            ┆ 18  ┆ 39          ┆ 0.461538         │
│ 1993-1994 ┆ Arsenal         ┆ Ian Wright                ┆ 23  ┆ 50          ┆ 0.46             │
│ 2005-2006 ┆ Charlton Ath    ┆ Darren Bent               ┆ 18  ┆ 40          ┆ 0.45             │
│ 2022-2023 ┆ Tottenham       ┆ Harry Kane                ┆ 30  ┆ 68          ┆ 0.441176         │
│ 2019-2020 ┆ Norwich City    ┆ Teemu Pukki               ┆ 11  ┆ 25          ┆ 0.44             │
│ 1994-1995 ┆ Blackburn       ┆ Alan Shearer              ┆ 34  ┆ 78          ┆ 0.435897         │
│ 2003-2004 ┆ Arsenal         ┆ Thierry Henry             ┆ 30  ┆ 69          ┆ 0.434783         │
│ 2019-2020 ┆ Southampton     ┆ Danny Ings                ┆ 22  ┆ 51          ┆ 0.431373         │
│ 2003-2004 ┆ Newcastle Utd   ┆ Alan Shearer              ┆ 22  ┆ 51          ┆ 0.431373         │
│ 2016-2017 ┆ Everton         ┆ Romelu Lukaku             ┆ 25  ┆ 58          ┆ 0.431034         │
│ 2017-2018 ┆ Tottenham       ┆ Harry Kane                ┆ 30  ┆ 70          ┆ 0.428571         │
│ 2020-2021 ┆ Sheffield Utd   ┆ David McGoldrick          ┆ 8   ┆ 19          ┆ 0.421053         │
│ 1993-1994 ┆ Newcastle Utd   ┆ Andy Cole                 ┆ 34  ┆ 81          ┆ 0.419753         │
│ 2014-2015 ┆ Aston Villa     ┆ Christian Benteke         ┆ 13  ┆ 31          ┆ 0.419355         │
│ 1995-1996 ┆ Liverpool       ┆ Robbie Fowler             ┆ 28  ┆ 68          ┆ 0.411765         │
│ 2011-2012 ┆ Arsenal         ┆ Robin van Persie          ┆ 30  ┆ 73          ┆ 0.410959         │
│ 1994-1995 ┆ Liverpool       ┆ Robbie Fowler             ┆ 25  ┆ 61          ┆ 0.409836         │
│ 2005-2006 ┆ Arsenal         ┆ Thierry Henry             ┆ 27  ┆ 66          ┆ 0.409091         │
│ 2014-2015 ┆ Burnley         ┆ Danny Ings                ┆ 11  ┆ 27          ┆ 0.407407         │
│ 2006-2007 ┆ Charlton Ath    ┆ Darren Bent               ┆ 13  ┆ 32          ┆ 0.40625          │
│ 2012-2013 ┆ Aston Villa     ┆ Christian Benteke         ┆ 19  ┆ 47          ┆ 0.404255         │
│ 1994-1995 ┆ QPR             ┆ Les Ferdinand             ┆ 24  ┆ 60          ┆ 0.4              │
│ 2007-2008 ┆ Manchester Utd  ┆ Cristiano Ronaldo         ┆ 31  ┆ 78          ┆ 0.397436         │
│ 2003-2004 ┆ Birmingham City ┆ Mikael Forssell           ┆ 17  ┆ 43          ┆ 0.395349         │
│ 2015-2016 ┆ Watford         ┆ Odion Ighalo              ┆ 15  ┆ 38          ┆ 0.394737         │
│ 2019-2020 ┆ Arsenal         ┆ Pierre-Emerick Aubameyang ┆ 22  ┆ 56          ┆ 0.392857         │
│ 2022-2023 ┆ Manchester City ┆ Erling Haaland            ┆ 36  ┆ 92          ┆ 0.391304         │
│ 1997-1998 ┆ Coventry City   ┆ Dion Dublin               ┆ 18  ┆ 46          ┆ 0.391304         │
│ 1993-1994 ┆ Norwich City    ┆ Chris Sutton              ┆ 25  ┆ 64          ┆ 0.390625         │
│ 2017-2018 ┆ Liverpool       ┆ Mohamed Salah             ┆ 32  ┆ 82          ┆ 0.390244         │
│ 1999-2000 ┆ Newcastle Utd   ┆ Alan Shearer              ┆ 23  ┆ 59          ┆ 0.38983          │
│ 2011-2012 ┆ Blackburn       ┆ Yakubu Aiyegbeni          ┆ 17  ┆ 44          ┆ 0.386364         │
│ 2011-2012 ┆ Fulham          ┆ Clint Dempsey             ┆ 17  ┆ 44          ┆ 0.386364         │
│ 2012-2013 ┆ Swansea City    ┆ Michu                     ┆ 18  ┆ 47          ┆ 0.382979         │
│ 1993-1994 ┆ Everton         ┆ Tony Cottee               ┆ 16  ┆ 42          ┆ 0.380952         │
│ 2007-2008 ┆ Blackburn       ┆ Roque Santa Cruz          ┆ 19  ┆ 50          ┆ 0.38             │
│ 2001-2002 ┆ Sunderland      ┆ Kevin Phillips            ┆ 11  ┆ 29          ┆ 0.37931          │
│ 1995-1996 ┆ Newcastle Utd   ┆ Les Ferdinand             ┆ 25  ┆ 66          ┆ 0.378788         │
│ 2014-2015 ┆ West Brom       ┆ Saido Berahino            ┆ 14  ┆ 37          ┆ 0.378378         │
│ 2017-2018 ┆ Leicester City  ┆ Jamie Vardy               ┆ 20  ┆ 53          ┆ 0.377358         │
│ 2020-2021 ┆ Burnley         ┆ Chris Wood                ┆ 12  ┆ 32          ┆ 0.375            │
└───────────┴─────────────────┴───────────────────────────┴─────┴─────────────┴──────────────────┘

In [73]:
foo.sort(by="total_goals", descending=True)

shape: (18_100, 9)
┌────────────────┬────────────────┬─────┬──────┬───┬─────┬─────────────┬───────────────┬───────────┐
│ Squad          ┆ Player         ┆ Age ┆ Min  ┆ … ┆ Ast ┆ total_goals ┆ prop_total_go ┆ season    │
│ ---            ┆ ---            ┆ --- ┆ ---  ┆   ┆ --- ┆ ---         ┆ als           ┆ ---       │
│ str            ┆ str            ┆ i16 ┆ i16  ┆   ┆ i16 ┆ i16         ┆ ---           ┆ str       │
│                ┆                ┆     ┆      ┆   ┆     ┆             ┆ f32           ┆           │
╞════════════════╪════════════════╪═════╪══════╪═══╪═════╪═════════════╪═══════════════╪═══════════╡
│ Manchester     ┆ Sergio Agüero  ┆ 29  ┆ 1963 ┆ … ┆ 6   ┆ 103         ┆ 0.203883      ┆ 2017-2018 │
│ City           ┆                ┆     ┆      ┆   ┆     ┆             ┆               ┆           │
│ Manchester     ┆ Claudio Bravo  ┆ 34  ┆ 226  ┆ … ┆ 0   ┆ 103         ┆ 0.0           ┆ 2017-2018 │
│ City           ┆                ┆     ┆      ┆   ┆     ┆             ┆               ┆           │
│ Manchester     ┆ Danilo         ┆ 26  ┆ 1349 ┆ … ┆ 2   ┆ 103         ┆ 0.029126      ┆ 2017-2018 │
│ City           ┆                ┆     ┆      ┆   ┆     ┆             ┆               ┆           │
│ Manchester     ┆ Kevin De       ┆ 26  ┆ 3073 ┆ … ┆ 16  ┆ 103         ┆ 0.07767       ┆ 2017-2018 │
│ City           ┆ Bruyne         ┆     ┆      ┆   ┆     ┆             ┆               ┆           │
│ Manchester     ┆ Fabian Delph   ┆ 27  ┆ 1741 ┆ … ┆ 2   ┆ 103         ┆ 0.009709      ┆ 2017-2018 │
│ City           ┆                ┆     ┆      ┆   ┆     ┆             ┆               ┆           │
│ …              ┆ …              ┆ …   ┆ …    ┆ … ┆ …   ┆ …           ┆ …             ┆ …         │
│ Derby County   ┆ Mile           ┆ 28  ┆ 688  ┆ … ┆ 1   ┆ 19          ┆ 0.0           ┆ 2007-2008 │
│                ┆ Sterjovski     ┆     ┆      ┆   ┆     ┆             ┆               ┆           │
│ Derby County   ┆ Alan Stubbs    ┆ 35  ┆ 645  ┆ … ┆ 0   ┆ 19          ┆ 0.0           ┆ 2007-2008 │
│ Derby County   ┆ Gary Teale     ┆ 29  ┆ 917  ┆ … ┆ 1   ┆ 19          ┆ 0.0           ┆ 2007-2008 │
│ Derby County   ┆ Andy Todd      ┆ 32  ┆ 1361 ┆ … ┆ 1   ┆ 19          ┆ 0.052632      ┆ 2007-2008 │
│ Derby County   ┆ Emanuel Villa  ┆ 25  ┆ 930  ┆ … ┆ 0   ┆ 19          ┆ 0.157895      ┆ 2007-2008 │
└────────────────┴────────────────┴─────┴──────┴───┴─────┴─────────────┴───────────────┴───────────┘

In [23]:
for i, (season, champ) in enumerate(CHAMPIONS.items()):
    pdf = html_to_flat_dataframe(Path(f"data/premier-league/fbref_{season}.html"))
    pldf = pl.from_pandas(pdf).filter(pl.col("Squad").eq(champ))

    goal_distribution: pl.DataFrame = pldf.with_columns(
        pl.lit(season).alias("Season"),
        pl.lit(champ).alias("Champion"),
        pl.col("Gls").sum().alias("squad_goals").cast(pl.Int16),
        pl.col("Gls").truediv(pl.col("Gls").sum()).alias("prop_squad_goals"),
    ).sort(by="prop_squad_goals", descending=True)

    distn_squad: pl.Series = goal_distribution.select("prop_squad_goals").to_series()

    distn_scorers: pl.Series = (
        goal_distribution.filter(pl.col("Gls").gt(0))
        .select("prop_squad_goals")
        .to_series()
    )
    wd_squad = wasserstein_distance(uniform_n(distn_squad), distn_squad)
    wd_scorers = wasserstein_distance(uniform_n(distn_scorers), distn_scorers)
    ed_squad = energy_distance(uniform_n(distn_squad), distn_squad)
    ed_scorers = energy_distance(uniform_n(distn_scorers), distn_scorers)

    distn_dist_df = goal_distribution.with_columns(
        max_prop_squad_goals=pl.lit(distn_scorers.max()),
        wass_dist_squad=pl.lit(wd_squad),
        wass_dist_scorers=pl.lit(wd_scorers),
        ener_dist_squad=pl.lit(ed_squad),
        ener_dist_scorers=pl.lit(ed_scorers),
    )
    print(distn_dist_df)

    all_squads[i] = distn_dist_df.select(
        "Season",
        "Champion",
        "squad_goals",
        "max_prop_squad_goals",
        "wass_dist_squad",
        "wass_dist_scorers",
        "ener_dist_squad",
        "ener_dist_scorers",
    ).slice(0, 1)

shape: (24, 15)
┌───────────┬─────────────┬─────┬──────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ Squad     ┆ Player      ┆ Age ┆ Min  ┆ … ┆ wass_dist_s ┆ wass_dist_s ┆ ener_dist_s ┆ ener_dist_s │
│ ---       ┆ ---         ┆ --- ┆ ---  ┆   ┆ quad        ┆ corers      ┆ quad        ┆ corers      │
│ str       ┆ str         ┆ i16 ┆ i16  ┆   ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│           ┆             ┆     ┆      ┆   ┆ f64         ┆ f64         ┆ f64         ┆ f64         │
╞═══════════╪═════════════╪═════╪══════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ Liverpool ┆ Mohamed     ┆ 32  ┆ 3371 ┆ … ┆ 0.048243    ┆ 0.060294    ┆ 0.186668    ┆ 0.201708    │
│           ┆ Salah       ┆     ┆      ┆   ┆             ┆             ┆             ┆             │
│ Liverpool ┆ Luis Díaz   ┆ 27  ┆ 2399 ┆ … ┆ 0.048243    ┆ 0.060294    ┆ 0.186668    ┆ 0.201708    │
│ Liverpool ┆ Cody Gakpo  ┆ 25  ┆ 1935 ┆ … ┆ 0.048243    ┆ 0.060294    ┆ 0.186668    ┆ 0.201708    │
│ Liverpool ┆ Diogo Jota  ┆ 27  ┆ 1196 ┆ … ┆ 0.048243    ┆ 0.060294    ┆ 0.186668    ┆ 0.201708    │
│ Liverpool ┆ Dominik     ┆ 23  ┆ 2491 ┆ … ┆ 0.048243    ┆ 0.060294    ┆ 0.186668    ┆ 0.201708    │
│           ┆ Szoboszlai  ┆     ┆      ┆   ┆             ┆             ┆             ┆             │
│ …         ┆ …           ┆ …   ┆ …    ┆ … ┆ …           ┆ …           ┆ …           ┆ …           │
│ Liverpool ┆ Vitezslav   ┆ 23  ┆ 12   ┆ … ┆ 0.048243    ┆ 0.060294    ┆ 0.186668    ┆ 0.201708    │
│           ┆ Jaros       ┆     ┆      ┆   ┆             ┆             ┆             ┆             │
│ Liverpool ┆ Caoimhín    ┆ 25  ┆ 900  ┆ … ┆ 0.048243    ┆ 0.060294    ┆ 0.186668    ┆ 0.201708    │
│           ┆ Kelleher    ┆     ┆      ┆   ┆             ┆             ┆             ┆             │
│ Liverpool ┆ Jarell      ┆ 21  ┆ 495  ┆ … ┆ 0.048243    ┆ 0.060294    ┆ 0.186668    ┆ 0.201708    │
│           ┆ Quansah     ┆     ┆      ┆   ┆             ┆             ┆             ┆             │
│ Liverpool ┆ Andrew      ┆ 30  ┆ 2482 ┆ … ┆ 0.048243    ┆ 0.060294    ┆ 0.186668    ┆ 0.201708    │
│           ┆ Robertson   ┆     ┆      ┆   ┆             ┆             ┆             ┆             │
│ Liverpool ┆ Kostas      ┆ 28  ┆ 837  ┆ … ┆ 0.048243    ┆ 0.060294    ┆ 0.186668    ┆ 0.201708    │
│           ┆ Tsimikas    ┆     ┆      ┆   ┆             ┆             ┆             ┆             │
└───────────┴─────────────┴─────┴──────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘
shape: (25, 15)
┌─────────────┬─────────────┬─────┬──────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ Squad       ┆ Player      ┆ Age ┆ Min  ┆ … ┆ wass_dist_s ┆ wass_dist_s ┆ ener_dist_ ┆ ener_dist_ │
│ ---         ┆ ---         ┆ --- ┆ ---  ┆   ┆ quad        ┆ corers      ┆ squad      ┆ scorers    │
│ str         ┆ str         ┆ i16 ┆ i16  ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│             ┆             ┆     ┆      ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞═════════════╪═════════════╪═════╪══════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Manchester  ┆ Erling      ┆ 23  ┆ 2552 ┆ … ┆ 0.044834    ┆ 0.056643    ┆ 0.178123   ┆ 0.20305    │
│ City        ┆ Haaland     ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Phil Foden  ┆ 23  ┆ 2857 ┆ … ┆ 0.044834    ┆ 0.056643    ┆ 0.178123   ┆ 0.20305    │
│ City        ┆             ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Julián      ┆ 23  ┆ 2647 ┆ … ┆ 0.044834    ┆ 0.056643    ┆ 0.178123   ┆ 0.20305    │
│ City        ┆ Álvarez     ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Rodri       ┆ 27  ┆ 2931 ┆ … ┆ 0.044834    ┆ 0.056643    ┆ 0.178123   ┆ 0.20305    │
│ City        ┆             ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Bernardo    ┆ 28  ┆ 2578 ┆ … ┆ 0.044834    ┆ 0.056643    ┆ 0.178123   ┆ 0.20305    │
│ City        ┆ Silva       ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ …           ┆ …           ┆ …   ┆ …    ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ Manchester  ┆ Matheus     ┆ 24  ┆ 661  ┆ … ┆ 0.044834    ┆ 0.056643    ┆ 0.178123   ┆ 0.20305    │
│ City        ┆ Nunes       ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Stefan      ┆ 30  ┆ 635  ┆ … ┆ 0.044834    ┆ 0.056643    ┆ 0.178123   ┆ 0.20305    │
│ City        ┆ Ortega      ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Cole Palmer ┆ 21  ┆ 11   ┆ … ┆ 0.044834    ┆ 0.056643    ┆ 0.178123   ┆ 0.20305    │
│ City        ┆             ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Kalvin      ┆ 27  ┆ 93   ┆ … ┆ 0.044834    ┆ 0.056643    ┆ 0.178123   ┆ 0.20305    │
│ City        ┆ Phillips    ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Kyle Walker ┆ 33  ┆ 2767 ┆ … ┆ 0.044834    ┆ 0.056643    ┆ 0.178123   ┆ 0.20305    │
│ City        ┆             ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
└─────────────┴─────────────┴─────┴──────┴───┴─────────────┴─────────────┴────────────┴────────────┘
shape: (24, 15)
┌─────────────┬─────────────┬─────┬──────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ Squad       ┆ Player      ┆ Age ┆ Min  ┆ … ┆ wass_dist_s ┆ wass_dist_s ┆ ener_dist_ ┆ ener_dist_ │
│ ---         ┆ ---         ┆ --- ┆ ---  ┆   ┆ quad        ┆ corers      ┆ squad      ┆ scorers    │
│ str         ┆ str         ┆ i16 ┆ i16  ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│             ┆             ┆     ┆      ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞═════════════╪═════════════╪═════╪══════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Manchester  ┆ Erling      ┆ 22  ┆ 2769 ┆ … ┆ 0.049215    ┆ 0.060386    ┆ 0.189353   ┆ 0.192711   │
│ City        ┆ Haaland     ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Phil Foden  ┆ 22  ┆ 1842 ┆ … ┆ 0.049215    ┆ 0.060386    ┆ 0.189353   ┆ 0.192711   │
│ City        ┆             ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Julián      ┆ 22  ┆ 1465 ┆ … ┆ 0.049215    ┆ 0.060386    ┆ 0.189353   ┆ 0.192711   │
│ City        ┆ Álvarez     ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ İlkay       ┆ 31  ┆ 2353 ┆ … ┆ 0.049215    ┆ 0.060386    ┆ 0.189353   ┆ 0.192711   │
│ City        ┆ Gündoğan    ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Kevin De    ┆ 31  ┆ 2417 ┆ … ┆ 0.049215    ┆ 0.060386    ┆ 0.189353   ┆ 0.192711   │
│ City        ┆ Bruyne      ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ …           ┆ …           ┆ …   ┆ …    ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ Manchester  ┆ Stefan      ┆ 29  ┆ 270  ┆ … ┆ 0.049215    ┆ 0.060386    ┆ 0.189353   ┆ 0.192711   │
│ City        ┆ Ortega      ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Cole Palmer ┆ 20  ┆ 370  ┆ … ┆ 0.049215    ┆ 0.060386    ┆ 0.189353   ┆ 0.192711   │
│ City        ┆             ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Máximo      ┆ 19  ┆ 19   ┆ … ┆ 0.049215    ┆ 0.060386    ┆ 0.189353   ┆ 0.192711   │
│ City        ┆ Perrone     ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Kalvin      ┆ 26  ┆ 300  ┆ … ┆ 0.049215    ┆ 0.060386    ┆ 0.189353   ┆ 0.192711   │
│ City        ┆ Phillips    ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Kyle Walker ┆ 32  ┆ 1958 ┆ … ┆ 0.049215    ┆ 0.060386    ┆ 0.189353   ┆ 0.192711   │
│ City        ┆             ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
└─────────────┴─────────────┴─────┴──────┴───┴─────────────┴─────────────┴────────────┴────────────┘
shape: (26, 15)
┌─────────────┬─────────────┬─────┬──────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ Squad       ┆ Player      ┆ Age ┆ Min  ┆ … ┆ wass_dist_s ┆ wass_dist_s ┆ ener_dist_ ┆ ener_dist_ │
│ ---         ┆ ---         ┆ --- ┆ ---  ┆   ┆ quad        ┆ corers      ┆ squad      ┆ scorers    │
│ str         ┆ str         ┆ i16 ┆ i16  ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│             ┆             ┆     ┆      ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞═════════════╪═════════════╪═════╪══════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Manchester  ┆ Kevin De    ┆ 30  ┆ 2201 ┆ … ┆ 0.039879    ┆ 0.040365    ┆ 0.176428   ┆ 0.17446    │
│ City        ┆ Bruyne      ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Raheem      ┆ 26  ┆ 2128 ┆ … ┆ 0.039879    ┆ 0.040365    ┆ 0.176428   ┆ 0.17446    │
│ City        ┆ Sterling    ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Riyad       ┆ 30  ┆ 1498 ┆ … ┆ 0.039879    ┆ 0.040365    ┆ 0.176428   ┆ 0.17446    │
│ City        ┆ Mahrez      ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Phil Foden  ┆ 21  ┆ 2128 ┆ … ┆ 0.039879    ┆ 0.040365    ┆ 0.176428   ┆ 0.17446    │
│ City        ┆             ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ İlkay       ┆ 30  ┆ 1857 ┆ … ┆ 0.039879    ┆ 0.040365    ┆ 0.176428   ┆ 0.17446    │
│ City        ┆ Gündoğan    ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ …           ┆ …           ┆ …   ┆ …    ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ Manchester  ┆ Benjamin    ┆ 27  ┆ 78   ┆ … ┆ 0.039879    ┆ 0.040365    ┆ 0.176428   ┆ 0.17446    │
│ City        ┆ Mendy       ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Cole Palmer ┆ 19  ┆ 123  ┆ … ┆ 0.039879    ┆ 0.040365    ┆ 0.176428   ┆ 0.17446    │
│ City        ┆             ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Zack        ┆ 26  ┆ 90   ┆ … ┆ 0.039879    ┆ 0.040365    ┆ 0.176428   ┆ 0.17446    │
│ City        ┆ Steffen     ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Kyle Walker ┆ 31  ┆ 1755 ┆ … ┆ 0.039879    ┆ 0.040365    ┆ 0.176428   ┆ 0.17446    │
│ City        ┆             ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Oleksandr   ┆ 24  ┆ 1047 ┆ … ┆ 0.039879    ┆ 0.040365    ┆ 0.176428   ┆ 0.17446    │
│ City        ┆ Zinchenko   ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
└─────────────┴─────────────┴─────┴──────┴───┴─────────────┴─────────────┴────────────┴────────────┘
shape: (24, 15)
┌─────────────┬─────────────┬─────┬──────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ Squad       ┆ Player      ┆ Age ┆ Min  ┆ … ┆ wass_dist_s ┆ wass_dist_s ┆ ener_dist_ ┆ ener_dist_ │
│ ---         ┆ ---         ┆ --- ┆ ---  ┆   ┆ quad        ┆ corers      ┆ squad      ┆ scorers    │
│ str         ┆ str         ┆ i16 ┆ i16  ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│             ┆             ┆     ┆      ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞═════════════╪═════════════╪═════╪══════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Manchester  ┆ İlkay       ┆ 29  ┆ 2029 ┆ … ┆ 0.040904    ┆ 0.041349    ┆ 0.177255   ┆ 0.178386   │
│ City        ┆ Gündoğan    ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Raheem      ┆ 25  ┆ 2536 ┆ … ┆ 0.040904    ┆ 0.041349    ┆ 0.177255   ┆ 0.178386   │
│ City        ┆ Sterling    ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Phil Foden  ┆ 20  ┆ 1616 ┆ … ┆ 0.040904    ┆ 0.041349    ┆ 0.177255   ┆ 0.178386   │
│ City        ┆             ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Gabriel     ┆ 23  ┆ 2063 ┆ … ┆ 0.040904    ┆ 0.041349    ┆ 0.177255   ┆ 0.178386   │
│ City        ┆ Jesus       ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Riyad       ┆ 29  ┆ 1949 ┆ … ┆ 0.040904    ┆ 0.041349    ┆ 0.177255   ┆ 0.178386   │
│ City        ┆ Mahrez      ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ …           ┆ …           ┆ …   ┆ …    ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ Manchester  ┆ Fernandinho ┆ 35  ┆ 1188 ┆ … ┆ 0.040904    ┆ 0.041349    ┆ 0.177255   ┆ 0.178386   │
│ City        ┆             ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Eric García ┆ 19  ┆ 383  ┆ … ┆ 0.040904    ┆ 0.041349    ┆ 0.177255   ┆ 0.178386   │
│ City        ┆             ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Aymeric     ┆ 26  ┆ 1344 ┆ … ┆ 0.040904    ┆ 0.041349    ┆ 0.177255   ┆ 0.178386   │
│ City        ┆ Laporte     ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Zack        ┆ 25  ┆ 90   ┆ … ┆ 0.040904    ┆ 0.041349    ┆ 0.177255   ┆ 0.178386   │
│ City        ┆ Steffen     ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Oleksandr   ┆ 23  ┆ 1478 ┆ … ┆ 0.040904    ┆ 0.041349    ┆ 0.177255   ┆ 0.178386   │
│ City        ┆ Zinchenko   ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
└─────────────┴─────────────┴─────┴──────┴───┴─────────────┴─────────────┴────────────┴────────────┘
shape: (24, 15)
┌───────────┬─────────────┬─────┬──────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ Squad     ┆ Player      ┆ Age ┆ Min  ┆ … ┆ wass_dist_s ┆ wass_dist_s ┆ ener_dist_s ┆ ener_dist_s │
│ ---       ┆ ---         ┆ --- ┆ ---  ┆   ┆ quad        ┆ corers      ┆ quad        ┆ corers      │
│ str       ┆ str         ┆ i16 ┆ i16  ┆   ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│           ┆             ┆     ┆      ┆   ┆ f64         ┆ f64         ┆ f64         ┆ f64         │
╞═══════════╪═════════════╪═════╪══════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ Liverpool ┆ Mohamed     ┆ 27  ┆ 2876 ┆ … ┆ 0.040035    ┆ 0.044607    ┆ 0.162472    ┆ 0.175166    │
│           ┆ Salah       ┆     ┆      ┆   ┆             ┆             ┆             ┆             │
│ Liverpool ┆ Sadio Mané  ┆ 27  ┆ 2747 ┆ … ┆ 0.040035    ┆ 0.044607    ┆ 0.162472    ┆ 0.175166    │
│ Liverpool ┆ Roberto     ┆ 27  ┆ 2988 ┆ … ┆ 0.040035    ┆ 0.044607    ┆ 0.162472    ┆ 0.175166    │
│           ┆ Firmino     ┆     ┆      ┆   ┆             ┆             ┆             ┆             │
│ Liverpool ┆ Virgil van  ┆ 28  ┆ 3420 ┆ … ┆ 0.040035    ┆ 0.044607    ┆ 0.162472    ┆ 0.175166    │
│           ┆ Dijk        ┆     ┆      ┆   ┆             ┆             ┆             ┆             │
│ Liverpool ┆ Trent Alexa ┆ 20  ┆ 3175 ┆ … ┆ 0.040035    ┆ 0.044607    ┆ 0.162472    ┆ 0.175166    │
│           ┆ nder-Arnold ┆     ┆      ┆   ┆             ┆             ┆             ┆             │
│ …         ┆ …           ┆ …   ┆ …    ┆ … ┆ …           ┆ …           ┆ …           ┆ …           │
│ Liverpool ┆ Harvey      ┆ 16  ┆ 8    ┆ … ┆ 0.040035    ┆ 0.044607    ┆ 0.162472    ┆ 0.175166    │
│           ┆ Elliott     ┆     ┆      ┆   ┆             ┆             ┆             ┆             │
│ Liverpool ┆ Joe Gomez   ┆ 22  ┆ 2004 ┆ … ┆ 0.040035    ┆ 0.044607    ┆ 0.162472    ┆ 0.175166    │
│ Liverpool ┆ Dejan       ┆ 30  ┆ 777  ┆ … ┆ 0.040035    ┆ 0.044607    ┆ 0.162472    ┆ 0.175166    │
│           ┆ Lovren      ┆     ┆      ┆   ┆             ┆             ┆             ┆             │
│ Liverpool ┆ Takumi      ┆ 24  ┆ 249  ┆ … ┆ 0.040035    ┆ 0.044607    ┆ 0.162472    ┆ 0.175166    │
│           ┆ Minamino    ┆     ┆      ┆   ┆             ┆             ┆             ┆             │
│ Liverpool ┆ Neco        ┆ 18  ┆ 230  ┆ … ┆ 0.040035    ┆ 0.044607    ┆ 0.162472    ┆ 0.175166    │
│           ┆ Williams    ┆     ┆      ┆   ┆             ┆             ┆             ┆             │
└───────────┴─────────────┴─────┴──────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘
shape: (21, 15)
┌─────────────┬─────────────┬─────┬──────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ Squad       ┆ Player      ┆ Age ┆ Min  ┆ … ┆ wass_dist_s ┆ wass_dist_s ┆ ener_dist_ ┆ ener_dist_ │
│ ---         ┆ ---         ┆ --- ┆ ---  ┆   ┆ quad        ┆ corers      ┆ squad      ┆ scorers    │
│ str         ┆ str         ┆ i16 ┆ i16  ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│             ┆             ┆     ┆      ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞═════════════╪═════════════╪═════╪══════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Manchester  ┆ Sergio      ┆ 30  ┆ 2459 ┆ … ┆ 0.048491    ┆ 0.047766    ┆ 0.190476   ┆ 0.172888   │
│ City        ┆ Agüero      ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Raheem      ┆ 23  ┆ 2771 ┆ … ┆ 0.048491    ┆ 0.047766    ┆ 0.190476   ┆ 0.172888   │
│ City        ┆ Sterling    ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Leroy Sané  ┆ 22  ┆ 1867 ┆ … ┆ 0.048491    ┆ 0.047766    ┆ 0.190476   ┆ 0.172888   │
│ City        ┆             ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Gabriel     ┆ 21  ┆ 1036 ┆ … ┆ 0.048491    ┆ 0.047766    ┆ 0.190476   ┆ 0.172888   │
│ City        ┆ Jesus       ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Riyad       ┆ 27  ┆ 1343 ┆ … ┆ 0.048491    ┆ 0.047766    ┆ 0.190476   ┆ 0.172888   │
│ City        ┆ Mahrez      ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ …           ┆ …           ┆ …   ┆ …    ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ Manchester  ┆ Ederson     ┆ 24  ┆ 3420 ┆ … ┆ 0.048491    ┆ 0.047766    ┆ 0.190476   ┆ 0.172888   │
│ City        ┆             ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Benjamin    ┆ 24  ┆ 900  ┆ … ┆ 0.048491    ┆ 0.047766    ┆ 0.190476   ┆ 0.172888   │
│ City        ┆ Mendy       ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Nicolás     ┆ 30  ┆ 1236 ┆ … ┆ 0.048491    ┆ 0.047766    ┆ 0.190476   ┆ 0.172888   │
│ City        ┆ Otamendi    ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ John Stones ┆ 24  ┆ 1764 ┆ … ┆ 0.048491    ┆ 0.047766    ┆ 0.190476   ┆ 0.172888   │
│ City        ┆             ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
│ Manchester  ┆ Oleksandr   ┆ 21  ┆ 1151 ┆ … ┆ 0.048491    ┆ 0.047766    ┆ 0.190476   ┆ 0.172888   │
│ City        ┆ Zinchenko   ┆     ┆      ┆   ┆             ┆             ┆            ┆            │
└─────────────┴─────────────┴─────┴──────┴───┴─────────────┴─────────────┴────────────┴────────────┘
shape: (25, 15)
┌─────────────┬─────────────┬─────┬──────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ Squad       ┆ Player      ┆ Age ┆ Min  ┆ … ┆ wass_dist_s ┆ wass_dist_s ┆ ener_dist_ ┆ ener_dist_ │
│ ---         ┆ ---         ┆ --- ┆ ---  ┆   ┆ quad        ┆ corers      ┆ squad      ┆ scorers    │
│ str         ┆ str         ┆ i16 ┆ i16  ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│             ┆             ┆     ┆      ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │

In [ ]:
pl.concat(all_squads).with_columns(
    pl.col("wass_dist_squad")
    .rank(method="dense", descending=True)
    .alias("rank_wass_dist_squad"),
    pl.col("wass_dist_scorers")
    .rank(method="dense", descending=True)
    .alias("rank_wass_dist_scorers"),
    pl.col("max_prop_squad_goals")
    .rank(method="dense", descending=True)
    .alias("rank_max_prop_squad_goals"),
).select(
    "Season",
    "Champion",
    "squad_goals",
    "max_prop_squad_goals",
    "rank_max_prop_squad_goals",
    "wass_dist_scorers",
    "rank_wass_dist_scorers",
).sort(by=pl.col("rank_wass_dist_scorers"))

shape: (33, 7)
┌───────────┬──────────────┬─────────────┬──────────────┬──────────────┬─────────────┬─────────────┐
│ Season    ┆ Champion     ┆ squad_goals ┆ max_prop_squ ┆ rank_max_pro ┆ wass_dist_s ┆ rank_wass_d │
│ ---       ┆ ---          ┆ ---         ┆ ad_goals     ┆ p_squad_goal ┆ corers      ┆ ist_scorers │
│ str       ┆ str          ┆ i16         ┆ ---          ┆ s            ┆ ---         ┆ ---         │
│           ┆              ┆             ┆ f64          ┆ ---          ┆ f64         ┆ u32         │
│           ┆              ┆             ┆              ┆ u32          ┆             ┆             │
╞═══════════╪══════════════╪═════════════╪══════════════╪══════════════╪═════════════╪═════════════╡
│ 1994-1995 ┆ Blackburn    ┆ 78          ┆ 0.435897     ┆ 1            ┆ 0.081161    ┆ 1           │
│ 2003-2004 ┆ Arsenal      ┆ 69          ┆ 0.434783     ┆ 2            ┆ 0.078502    ┆ 2           │
│ 2007-2008 ┆ Manchester   ┆ 78          ┆ 0.397436     ┆ 3            ┆ 0.076923    ┆ 3           │
│           ┆ Utd          ┆             ┆              ┆              ┆             ┆             │
│ 2002-2003 ┆ Manchester   ┆ 73          ┆ 0.342466     ┆ 6            ┆ 0.072045    ┆ 4           │
│           ┆ Utd          ┆             ┆              ┆              ┆             ┆             │
│ 2015-2016 ┆ Leicester    ┆ 68          ┆ 0.352941     ┆ 5            ┆ 0.070832    ┆ 5           │
│           ┆ City         ┆             ┆              ┆              ┆             ┆             │
│ 2009-2010 ┆ Chelsea      ┆ 99          ┆ 0.292929     ┆ 10           ┆ 0.065966    ┆ 6           │
│ 2001-2002 ┆ Arsenal      ┆ 79          ┆ 0.303797     ┆ 9            ┆ 0.065463    ┆ 7           │
│ 2022-2023 ┆ Manchester   ┆ 92          ┆ 0.391304     ┆ 4            ┆ 0.060386    ┆ 8           │
│           ┆ City         ┆             ┆              ┆              ┆             ┆             │
│ 2024-2025 ┆ Liverpool    ┆ 85          ┆ 0.341176     ┆ 7            ┆ 0.060294    ┆ 9           │
│ 2010-2011 ┆ Manchester   ┆ 75          ┆ 0.266667     ┆ 13           ┆ 0.058667    ┆ 10          │
│           ┆ Utd          ┆             ┆              ┆              ┆             ┆             │
│ 2023-2024 ┆ Manchester   ┆ 94          ┆ 0.287234     ┆ 11           ┆ 0.056643    ┆ 11          │
│           ┆ City         ┆             ┆              ┆              ┆             ┆             │
│ 1998-1999 ┆ Manchester   ┆ 78          ┆ 0.230769     ┆ 20           ┆ 0.05641     ┆ 12          │
│           ┆ Utd          ┆             ┆              ┆              ┆             ┆             │
│ 1993-1994 ┆ Manchester   ┆ 80          ┆ 0.225        ┆ 24           ┆ 0.056213    ┆ 13          │
│           ┆ Utd          ┆             ┆              ┆              ┆             ┆             │
│ 1997-1998 ┆ Arsenal      ┆ 66          ┆ 0.242424     ┆ 17           ┆ 0.055227    ┆ 14          │
│ 1995-1996 ┆ Manchester   ┆ 72          ┆ 0.194444     ┆ 30           ┆ 0.055062    ┆ 15          │
│           ┆ Utd          ┆             ┆              ┆              ┆             ┆             │
│ 2014-2015 ┆ Chelsea      ┆ 72          ┆ 0.277778     ┆ 12           ┆ 0.05309     ┆ 16          │
│ 1992-1993 ┆ Manchester   ┆ 66          ┆ 0.227273     ┆ 22           ┆ 0.052717    ┆ 17          │
│           ┆ Utd          ┆             ┆              ┆              ┆             ┆             │
│ 2005-2006 ┆ Chelsea      ┆ 71          ┆ 0.225352     ┆ 23           ┆ 0.051338    ┆ 18          │
│ 1999-2000 ┆ Manchester   ┆ 94          ┆ 0.212766     ┆ 25           ┆ 0.050862    ┆ 19          │
│           ┆ Utd          ┆             ┆              ┆              ┆             ┆             │
│ 2013-2014 ┆ Manchester   ┆ 97          ┆ 0.206186     ┆ 27           ┆ 0.050705    ┆ 20          │
│           ┆ City         ┆             ┆              ┆              ┆             ┆             │
│ 2016-2017 ┆ Chelsea      ┆ 83          ┆ 0.240964     ┆ 18           ┆ 0.050652    ┆ 21          │
│ 2008-2009 ┆ Manchester   ┆ 68          ┆ 0.264706     ┆ 14           ┆ 0.049632    ┆ 22          │
│           ┆ Utd          ┆             ┆              ┆              ┆             ┆             │
│ 2000-2001 ┆ Manchester   ┆ 76          ┆ 0.197368     ┆ 29           ┆ 0.048421    ┆ 23          │
│           ┆ Utd          ┆             ┆              ┆              ┆             ┆             │
│ 2004-2005 ┆ Chelsea      ┆ 71          ┆ 0.183099     ┆ 31           ┆ 0.048122    ┆ 24          │
│ 2018-2019 ┆ Manchester   ┆ 91          ┆ 0.230769     ┆ 19           ┆ 0.047766    ┆ 25          │
│           ┆ City         ┆             ┆              ┆              ┆             ┆             │
│ 2012-2013 ┆ Manchester   ┆ 80          ┆ 0.325        ┆ 8            ┆ 0.0475      ┆ 26          │
│           ┆ Utd          ┆             ┆              ┆              ┆             ┆             │
│ 2017-2018 ┆ Manchester   ┆ 103         ┆ 0.203883     ┆ 28           ┆ 0.046993    ┆ 27          │
│           ┆ City         ┆             ┆              ┆              ┆             ┆             │
│ 2011-2012 ┆ Manchester   ┆ 91          ┆ 0.252747     ┆ 16           ┆ 0.046532    ┆ 28          │
│           ┆ City         ┆             ┆              ┆              ┆             ┆             │
│ 1996-1997 ┆ Manchester   ┆ 71          ┆ 0.253521     ┆ 15           ┆ 0.045703    ┆ 29          │
│           ┆ Utd          ┆             ┆              ┆              ┆             ┆             │
│ 2019-2020 ┆ Liverpool    ┆ 83          ┆ 0.228916     ┆ 21           ┆ 0.044607    ┆ 30          │
│ 2006-2007 ┆ Manchester   ┆ 80          ┆ 0.2125       ┆ 26           ┆ 0.042301    ┆ 31          │
│           ┆ Utd          ┆             ┆              ┆              ┆             ┆             │
│ 2020-2021 ┆ Manchester   ┆ 82          ┆ 0.158537     ┆ 32           ┆ 0.041349    ┆ 32          │
│           ┆ City         ┆             ┆              ┆              ┆             ┆             │
│ 2021-2022 ┆ Manchester   ┆ 96          ┆ 0.15625      ┆ 33           ┆ 0.040365    ┆ 33          │
│           ┆ City         ┆             ┆              ┆              ┆             ┆             │
└───────────┴──────────────┴─────────────┴──────────────┴──────────────┴─────────────┴─────────────┘

\# Dirichlet and Statistical Distance
There is at least one [academic paper](https://www.sciencedirect.com/science/article/abs/pii/S0031320307003123) discussing the distance between Dirichlet distribution realizations, and a [smart-looking blog post](https://benmoran.wordpress.com/2012/07/11/distances-divergences-dirichlet-distributions/).

The form of the Dirichlet distribution imposes that $\alpha_k > 0,\, \, \, k=1,...,K$ and that $||\vec{\alpha}||_1 = 1,\,\,\, \vec{\alpha}\in\mathbb{R}^K$. This means that
$$\mathbb{R}^{K}_{\geq 0,\,\leq 1}\ni\vec{G}_{cs}\sim \text{Dir}(\vec{\alpha}, K)$$

Based on the above paper, only the Chernoff distance (which simplifies to the Bhattacharyya distance when $\lambda = \frac{1}{2}$) is appropriate as a distance metric between Dirichlet distributions. So, instead of using the energy distance and ~~Wasserstein~~ Kantorovich distance (see [here](https://en.wikipedia.org/wiki/Wasserstein_metric#)), we shall use the Bhattacharyya distance instead. **N.b.** this may be overkill/inappropriate/unnecessary because of the comparison to the "flat Dirichlet", a.k.a. $K$-dimension uniform.

## Chernoff Distance
$$J_C(\vec{\alpha}_a,\vec{\alpha}_b) = \ln\Gamma\bigg(\sum_{k=1}^{K}\lambda\alpha_{ak} + (1-\lambda)\alpha_{bk}\bigg) + \lambda\sum_{k=1}^{K}\ln\Gamma(\alpha_{ak}) + (1-\lambda)\sum_{k=1}^{K}\ln\Gamma(\alpha_{bk})$$

In [ ]:
s = goals25.select("prop_total_goals").to_series()
s

shape: (24,)
Series: 'prop_total_goals' [f64]
[
	0.341176
	0.152941
	0.117647
	0.070588
	0.070588
	…
	0.0
	0.0
	0.0
	0.0
	0.0
]

In [62]:
import numpy as np
from scipy.spatial import distance
from scipy.special import gamma, gammaln

assert distance.euclidean(s, s) == 0.0

In [38]:
# Is this the only multivariate distance metric in scipy?
distance.mahalanobis(s, s)

TypeError: mahalanobis() missing 1 required positional argument: 'VI'

In [42]:
s

shape: (24,)
Series: 'prop_total_goals' [f64]
[
	0.341176
	0.152941
	0.117647
	0.070588
	0.070588
	…
	0.0
	0.0
	0.0
	0.0
	0.0
]

## Distance to All-Mass-On-One-Component Vector
What is the distance between the observed $\mathbb{R}^{K}_{\geq 0,\,\leq 1}\ni\vec{G}^{*}$ and the opposite of a uniform (a vniform??) in the same space that is entirely "peaked" at one component?

Also, are these distances the same independent of which $k=1,...,K$ has all the mass?

In [50]:
# a "vniform" with all mass on the 0th element
v: np.ndarray = np.eye(len(s))
v0: pl.Series = pl.Series(v[0])
v1: pl.Series = pl.Series(v[1])
# etc.

In [58]:
np.cov([s, v0], rowvar=False).shape

(24, 24)

In [ ]:
distance.mahalanobis(
    s,
    v0,
    np.linalg.inv(np.cov([s, v0], rowvar=False)),
)

LinAlgError: Singular matrix

Okay, so whatever I'm doing is giving me covariance matrices that are not copacetic...

In [63]:
distance.euclidean(s, v0)

0.7015553654529681

In [64]:
distance.euclidean(s, v1)

0.9320142268394522

In [65]:
distance.euclidean(s, pl.Series(v[2]))

0.9691433094879516

Move on to roll my own Bhattacharyya distance.

In [66]:
def bhattacharyya(
    p: np.typing.ArrayLike,
    q: np.typing.ArrayLike,
) -> float:
    lmbda: float = 0.5
    return lmbda